services:
  backend:
    build:
      context: ./backend
    container_name: clb_backend
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://localhost:27017/clb_hienmau_husc
      - JWT_SECRET=MatKhauBiMatChoJWT
      - JWT_EXPIRE=24h
      - JWT_REFRESH_SECRET=MatKhauBiMatChoJWTRefresh
      - JWT_REFRESH_EXPIRE=7d
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:3001
    container_name: clb_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: clb_mongo
    command: ["mongod", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
