services:
  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/clb_hienmau_husc
      - JWT_SECRET=MatKhauBiMatChoJWT
      - JWT_EXPIRE=24h
      - JWT_REFRESH_SECRET=MatKhauBiMatChoJWTRefresh
      - JWT_REFRESH_EXPIRE=7d
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"